/**
 * IMPORTANT:
 * The index of each label MUST match the model's class index.
 * Do NOT reorder this list unless you retrain the model.
 */

export const MUSHROOM_LABELS: readonly string[] = [
  /* 000 */ 'Almond Mushroom',
  /* 001 */ 'Amanita Gemmata',
  /* 002 */ 'Amethyst Chanterelle',
  /* 003 */ 'Amethyst Deceiver',
  /* 004 */ 'Aniseed Funnel',
  /* 005 */ 'Ascot Hat',
  /* 006 */ 'Bay Bolete',
  /* 007 */ 'Bearded Milkcap',
  /* 008 */ 'Beechwood Sickener',
  /* 009 */ 'Beefsteak Fungus',
  /* 010 */ 'Birch Polypore',
  /* 011 */ 'Birch Woodwart',
  /* 012 */ 'Bitter Beech Bolete',
  /* 013 */ 'Bitter Bolete',
  /* 014 */ 'Black Bulgar',
  /* 015 */ 'Black Morel',
  /* 016 */ 'Blackening Brittlegill',
  /* 017 */ 'Blackening Polypore',
  /* 018 */ 'Blackening Waxcap',
  /* 019 */ 'Blue Roundhead',
  /* 020 */ 'Blushing Bracket',
  /* 021 */ 'Blushing Rosette',
  /* 022 */ 'Blushing Wood Mushroom',
  /* 023 */ 'Bovine Bolete',
  /* 024 */ 'Bronze Bolete',
  /* 025 */ 'Brown Birch Bolete',
  /* 026 */ 'Brown Rollrim',
  /* 027 */ 'Bruising Webcap',
  /* 028 */ 'Butter Cap',
  /* 029 */ 'Cauliflower Fungus',
  /* 030 */ 'Cedarwood Waxcap',
  /* 031 */ 'Chanterelle',
  /* 032 */ 'Charcoal Burner',
  /* 033 */ 'Chestnut Bolete',
  /* 034 */ 'Chicken Of The Woods',
  /* 035 */ 'Cinnamon Bracket',
  /* 036 */ 'Clouded Agaric',
  /* 037 */ 'Clustered Domecap',
  /* 038 */ 'Common Bonnet',
  /* 039 */ 'Common Inkcap',
  /* 040 */ 'Common Morel',
  /* 041 */ 'Common Puffball',
  /* 042 */ 'Common Rustgill',
  /* 043 */ 'Crimped Gill',
  /* 044 */ 'Crimson Waxcap',
  /* 045 */ 'Cucumber Cap',
  /* 046 */ 'Curry Milkcap',
  /* 047 */ 'Deadly Fibrecap',
  /* 048 */ 'Deadly Webcap',
  /* 049 */ 'Deathcap',
  /* 050 */ 'Deer Shield',
  /* 051 */ 'Destroying Angel',
  /* 052 */ 'Devils Bolete',
  /* 053 */ 'Dog Stinkhorn',
  /* 054 */ 'Dryads Saddle',
  /* 055 */ 'Dusky Puffball',
  /* 056 */ 'Dyers Mazegill',
  /* 057 */ 'Earthballs',
  /* 058 */ 'Egghead Mottlegill',
  /* 059 */ 'Elfin Saddle',
  /* 060 */ 'Fairy Ring Champignons',
  /* 061 */ 'False Chanterelle',
  /* 062 */ 'False Deathcap',
  /* 063 */ 'False Morel',
  /* 064 */ 'False Saffron Milkcap',
  /* 065 */ 'Fenugreek Milkcap',
  /* 066 */ 'Field Blewit',
  /* 067 */ 'Field Mushroom',
  /* 068 */ 'Fleecy Milkcap',
  /* 069 */ 'Fly Agaric',
  /* 070 */ 'Fools Funnel',
  /* 071 */ 'Fragrant Funnel',
  /* 072 */ 'Freckled Dapperling',
  /* 073 */ 'Frosted Chanterelle',
  /* 074 */ 'Funeral Bell',
  /* 075 */ 'Geranium Brittlegill',
  /* 076 */ 'Giant Funnel',
  /* 077 */ 'Giant Puffball',
  /* 078 */ 'Glistening Inkcap',
  /* 079 */ 'Golden Bootleg',
  /* 080 */ 'Golden Scalycap',
  /* 081 */ 'Golden Waxcap',
  /* 082 */ 'Greencracked Brittlegill',
  /* 083 */ 'Grey Knight',
  /* 084 */ 'Grey Spotted Amanita',
  /* 085 */ 'Grisettes',
  /* 086 */ 'Hairy Curtain Crust',
  /* 087 */ 'Heath Waxcap',
  /* 088 */ 'Hedgehog Fungus',
  /* 089 */ 'Hen Of The Woods',
  /* 090 */ 'Honey Fungus',
  /* 091 */ 'Hoof Fungus',
  /* 092 */ 'Horn Of Plenty',
  /* 093 */ 'Horse Mushroom',
  /* 094 */ 'Inky Mushroom',
  /* 095 */ 'Jelly Ears',
  /* 096 */ 'Jelly Tooth',
  /* 097 */ 'Jubilee Waxcap',
  /* 098 */ 'King Alfreds Cakes',
  /* 099 */ 'Larch Bolete',
  /* 100 */ 'Leccinum Albostipitatum',
  /* 101 */ 'Liberty Cap',
  /* 102 */ 'Lilac Bonnet',
  /* 103 */ 'Lilac Fibrecap',
  /* 104 */ 'Lions Mane',
  /* 105 */ 'Lurid Bolete',
  /* 106 */ 'Macro Mushroom',
  /* 107 */ 'Magpie Inkcap',
  /* 108 */ 'Meadow Waxcap',
  /* 109 */ 'Medusa Mushroom',
  /* 110 */ 'Morel',
  /* 111 */ 'Mosaic Puffball',
  /* 112 */ 'Oak Bolete',
  /* 113 */ 'Oak Mazegill',
  /* 114 */ 'Oak Polypore',
  /* 115 */ 'Ochre Brittlegill',
  /* 116 */ 'Old Man Of The Woods',
  /* 117 */ 'Orange Birch Bolete',
  /* 118 */ 'Orange Bolete',
  /* 119 */ 'Orange Grisette',
  /* 120 */ 'Orange Peel Fungus',
  /* 121 */ 'Oyster Mushroom',
  /* 122 */ 'Pale Oyster',
  /* 123 */ 'Panthercap',
  /* 124 */ 'Parasol',
  /* 125 */ 'Parrot Waxcap',
  /* 126 */ 'Pavement Mushroom',
  /* 127 */ 'Penny Bun',
  /* 128 */ 'Peppery Bolete',
  /* 129 */ 'Pestle Puffball',
  /* 130 */ 'Pine Bolete',
  /* 131 */ 'Pink Waxcap',
  /* 132 */ 'Plums And Custard',
  /* 133 */ 'Poison Pie',
  /* 134 */ 'Poplar Bell',
  /* 135 */ 'Poplar Fieldcap',
  /* 136 */ 'Porcelain Fungus',
  /* 137 */ 'Powdery Brittlegill',
  /* 138 */ 'Purple Brittlegill',
  /* 139 */ 'Red Belted Bracket',
  /* 140 */ 'Red Cracking Bolete',
  /* 141 */ 'Root Rot',
  /* 142 */ 'Rooting Bolete',
  /* 143 */ 'Rooting Shank',
  /* 144 */ 'Rosy Bonnet',
  /* 145 */ 'Ruby Bolete',
  /* 146 */ 'Saffron Milkcap',
  /* 147 */ 'Scaly Wood Mushroom',
  /* 148 */ 'Scarlet Caterpillarclub',
  /* 149 */ 'Scarlet Elfcup',
  /* 150 */ 'Scarlet Waxcap',
  /* 151 */ 'Scarletina Bolete',
  /* 152 */ 'Semifree Morel',
  /* 153 */ 'Sepia Bolete',
  /* 154 */ 'Shaggy Bracket',
  /* 155 */ 'Shaggy Inkcap',
  /* 156 */ 'Shaggy Parasol',
  /* 157 */ 'Shaggy Scalycap',
  /* 158 */ 'Sheathed Woodtuft',
  /* 159 */ 'Silky Rosegill',
  /* 160 */ 'Silverleaf Fungus',
  /* 161 */ 'Slender Parasol',
  /* 162 */ 'Slimy Waxcap',
  /* 163 */ 'Slippery Jack',
  /* 164 */ 'Smoky Bracket',
  /* 165 */ 'Snakeskin Grisette',
  /* 166 */ 'Snowy Waxcap',
  /* 167 */ 'Spectacular Rustgill',
  /* 168 */ 'Splendid Waxcap',
  /* 169 */ 'Splitgill',
  /* 170 */ 'Spotted Toughshank',
  /* 171 */ 'Spring Fieldcap',
  /* 172 */ 'St Georges Mushroom',
  /* 173 */ 'Stinkhorn',
  /* 174 */ 'Stinking Dapperling',
  /* 175 */ 'Stubble Rosegill',
  /* 176 */ 'Stump Puffball',
  /* 177 */ 'Suede Bolete',
  /* 178 */ 'Sulphur Tuft',
  /* 179 */ 'Summer Bolete',
  /* 180 */ 'Tawny Funnel',
  /* 181 */ 'Tawny Grisette',
  /* 182 */ 'Terracotta Hedgehog',
  /* 183 */ 'The Blusher',
  /* 184 */ 'The Deceiver',
  /* 185 */ 'The Goblet',
  /* 186 */ 'The Miller',
  /* 187 */ 'The Prince',
  /* 188 */ 'The Sickener',
  /* 189 */ 'Thimble Morel',
  /* 190 */ 'Tripe Fungus',
  /* 191 */ 'Trooping Funnel',
  /* 192 */ 'Truffles',
  /* 193 */ 'Tuberous Polypore',
  /* 194 */ 'Turkey Tail',
  /* 195 */ 'Velvet Shank',
  /* 196 */ 'Vermillion Waxcap',
  /* 197 */ 'Warted Amanita',
  /* 198 */ 'Weeping Widow',
  /* 199 */ 'White Dapperling',
  /* 200 */ 'White Domecap',
  /* 201 */ 'White False Death Cap',
  /* 202 */ 'White Fibrecap',
  /* 203 */ 'White Saddle',
  /* 204 */ 'Winter Chanterelle',
  /* 205 */ 'Wood Blewit',
  /* 206 */ 'Wood Mushroom',
  /* 207 */ 'Woodland Inkcap',
  /* 208 */ 'Woolly Milkcap',
  /* 209 */ 'Wrinkled Peach',
  /* 210 */ 'Yellow False Truffle',
  /* 211 */ 'Yellow Foot Waxcap',
  /* 212 */ 'Yellow Stagshorn',
  /* 213 */ 'Yellow Stainer',
  /* 214 */ 'Yellow Swamp Brittlegill',
] as const;

/**
 * Total number of classes the model supports
 */
export const MUSHROOM_CLASS_COUNT = MUSHROOM_LABELS.length;

/**
 * Safe label lookup
 */
export function getMushroomLabel(classId: number): string {
  if (
    Number.isNaN(classId) ||
    classId < 0 ||
    classId >= MUSHROOM_LABELS.length
  ) {
    return 'Unknown mushroom';
  }
  return MUSHROOM_LABELS[classId];
}
